services:
  traefik:
    image: traefik:v3.3
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "5433:5432"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./conf/traefik/traefik.yml:/traefik.yml:ro
    networks:
      - www

networks:
  www:
    name: www
    driver: bridge
