from . import analysis
from . import animated_energy_duration
from . import distribution_of_energy_demand
from . import energy_supplied_by_plugin_hour
from . import number_of_charges_by_hour
from . import number_of_charges_by_weekday
from . import plug_duration
from . import plug_duration_by_plugin_hour
from . import predictions
from . import stats
from . import tfm_plots
from . import total_energy_supplied_by_weekday