-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

CREATE SCHEMA IF NOT EXISTS evinsights;


ALTER TABLE IF EXISTS evinsights."ChargingSession" DROP CONSTRAINT IF EXISTS fk_charging_station_id;

ALTER TABLE IF EXISTS evinsights."ChargingSession" DROP CONSTRAINT IF EXISTS fk_dataset_id;

ALTER TABLE IF EXISTS evinsights."ChargingSession" DROP CONSTRAINT IF EXISTS fk_user_id;

ALTER TABLE IF EXISTS evinsights."ChargingStationForecast" DROP CONSTRAINT IF EXISTS fk_charging_station_id;

ALTER TABLE IF EXISTS evinsights."UserForecast" DROP CONSTRAINT IF EXISTS fk_user_id;



DROP TABLE IF EXISTS evinsights."ChargingSession";

CREATE TABLE IF NOT EXISTS evinsights."ChargingSession"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    plug_in_soc numeric(3, 0),
    plug_in_datetime timestamp without time zone,
    plug_out_datetime timestamp without time zone,
    charge_end_datetime timestamp without time zone,
    charge_end_datetime_presence boolean,
    energy_supplied numeric(12, 3),
    fk_dataset_id integer,
    fk_charging_station_id integer,
    fk_user_id integer,
    CONSTRAINT "ChargingSession_pkey" PRIMARY KEY (id)
);

DROP TABLE IF EXISTS evinsights."ChargingStation";

CREATE TABLE IF NOT EXISTS evinsights."ChargingStation"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    orig_id text COLLATE pg_catalog."default",
    manufacturer text COLLATE pg_catalog."default",
    model text COLLATE pg_catalog."default",
    type text COLLATE pg_catalog."default",
    num_plugs integer,
    max_charging_power numeric(12, 3),
    max_discharging_power numeric(12, 3),
    dataset_id integer,
    CONSTRAINT "ChargingStation_pkey" PRIMARY KEY (id)
);

DROP TABLE IF EXISTS evinsights."Dataset";

CREATE TABLE IF NOT EXISTS evinsights."Dataset"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name text COLLATE pg_catalog."default" NOT NULL,
    url text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    owner text COLLATE pg_catalog."default",
    country text COLLATE pg_catalog."default",
    region text COLLATE pg_catalog."default",
    city text COLLATE pg_catalog."default",
    file_name text COLLATE pg_catalog."default",
    file_type text COLLATE pg_catalog."default",
    delimiter text COLLATE pg_catalog."default",
    encoding text COLLATE pg_catalog."default",
    license text COLLATE pg_catalog."default",
    notes text COLLATE pg_catalog."default",
    charging_point_type text,
    CONSTRAINT "Dataset_pkey" PRIMARY KEY (id)
);

DROP TABLE IF EXISTS evinsights."User";

CREATE TABLE IF NOT EXISTS evinsights."User"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    orig_id text COLLATE pg_catalog."default",
    ev_id text COLLATE pg_catalog."default",
    ev_manufacturer text COLLATE pg_catalog."default",
    ev_model text COLLATE pg_catalog."default",
    ev_battery_capacity numeric(2, 0),
    ev_battery_type text COLLATE pg_catalog."default",
    ev_battery_useable_capacity numeric(2, 0),
    ev_v2g boolean,
    ev_max_charging_power numeric(12, 3),
    ev_max_discharging_power numeric(12, 3),
    dataset_id integer,
    CONSTRAINT "User_pkey" PRIMARY KEY (id)
);

DROP TABLE IF EXISTS evinsights."ChargingStationForecast";

CREATE TABLE IF NOT EXISTS evinsights."ChargingStationForecast"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    date date,
    energy numeric(12, 3),
    connections integer,
    experiment_id text,
    run_id text,
    created_at timestamp with time zone,
    fk_charging_station_id integer,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS evinsights."UserForecast";

CREATE TABLE IF NOT EXISTS evinsights."UserForecast"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    date date,
    energy numeric(12, 3),
    duration integer,
    experiment_id text,
    run_id text,
    created_at timestamp with time zone,
    fk_user_id integer,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS evinsights."ChargingSession"
    ADD CONSTRAINT fk_charging_station_id FOREIGN KEY (fk_charging_station_id)
    REFERENCES evinsights."ChargingStation" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS evinsights."ChargingSession"
    ADD CONSTRAINT fk_dataset_id FOREIGN KEY (fk_dataset_id)
    REFERENCES evinsights."Dataset" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS evinsights."ChargingSession"
    ADD CONSTRAINT fk_user_id FOREIGN KEY (fk_user_id)
    REFERENCES evinsights."User" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS evinsights."ChargingStationForecast"
    ADD CONSTRAINT fk_charging_station_id FOREIGN KEY (fk_charging_station_id)
    REFERENCES evinsights."ChargingStation" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS evinsights."UserForecast"
    ADD CONSTRAINT fk_user_id FOREIGN KEY (fk_user_id)
    REFERENCES evinsights."User" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;