-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.

-- Connect to the evinsights database
\c evinsights

BEGIN;

DROP SCHEMA IF EXISTS evinsights CASCADE;
CREATE SCHEMA IF NOT EXISTS evinsights;


ALTER TABLE IF EXISTS evinsights."ChargingSession" DROP CONSTRAINT IF EXISTS fk_charging_station_id;

ALTER TABLE IF EXISTS evinsights."ChargingSession" DROP CONSTRAINT IF EXISTS fk_dataset_id;

ALTER TABLE IF EXISTS evinsights."ChargingSession" DROP CONSTRAINT IF EXISTS fk_user_id;

ALTER TABLE IF EXISTS evinsights."ChargingStationForecast" DROP CONSTRAINT IF EXISTS fk_charging_station_id;

ALTER TABLE IF EXISTS evinsights."UserForecast" DROP CONSTRAINT IF EXISTS fk_user_id;

ALTER TABLE IF EXISTS evinsights."ChargingStation" DROP CONSTRAINT IF EXISTS fk_connector_id;

ALTER TABLE IF EXISTS evinsights."ChargingStation" DROP CONSTRAINT IF EXISTS fk_charging_point_type_id;


DROP TABLE IF EXISTS evinsights."Dataset";

CREATE TABLE IF NOT EXISTS evinsights."Dataset"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name text COLLATE pg_catalog."default" NOT NULL,
    url text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    owner text COLLATE pg_catalog."default",
    country text COLLATE pg_catalog."default",
    region text COLLATE pg_catalog."default",
    city text COLLATE pg_catalog."default",
    dataset_directory text COLLATE pg_catalog."default",
    file_name text COLLATE pg_catalog."default",
    file_type text COLLATE pg_catalog."default",
    delimiter text COLLATE pg_catalog."default",
    encoding text COLLATE pg_catalog."default",
    license text COLLATE pg_catalog."default",
    notes text COLLATE pg_catalog."default",
    charging_point_type text,
    CONSTRAINT "Dataset_pkey" PRIMARY KEY (id)
);

DROP TABLE IF EXISTS evinsights."ChargingPointType";

CREATE TABLE IF NOT EXISTS evinsights."ChargingPointType"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    name varchar(20),
    description text,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS evinsights."Connector";

CREATE TABLE IF NOT EXISTS evinsights."Connector"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    code varchar(20),
    current_type varchar(2),
    charging_level varchar(2),
    description text,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS evinsights."ElectricVehicle";

CREATE TABLE IF NOT EXISTS evinsights."ElectricVehicle"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    ev_manufacturer text COLLATE pg_catalog."default",
    ev_model text COLLATE pg_catalog."default",
    ev_battery_capacity_kWh numeric(12, 2),
    ev_battery_type text COLLATE pg_catalog."default",
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS evinsights."ChargingSession";

CREATE TABLE IF NOT EXISTS evinsights."ChargingSession"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    plug_in_soc numeric(3, 0),
    plug_in_datetime timestamp without time zone,
    plug_out_datetime timestamp without time zone,
    charge_end_datetime timestamp without time zone,
    charge_end_datetime_presence boolean,
    energy_supplied numeric(12, 3),
    fk_dataset_id integer,
    fk_charging_station_id integer,
    fk_user_id integer,
    CONSTRAINT "ChargingSession_pkey" PRIMARY KEY (id)
);

DROP TABLE IF EXISTS evinsights."ChargingStation";

CREATE TABLE IF NOT EXISTS evinsights."ChargingStation"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    orig_id text COLLATE pg_catalog."default",
    station_name text COLLATE pg_catalog."default",
    site_name text COLLATE pg_catalog."default",
    country text COLLATE pg_catalog."default",
    city text COLLATE pg_catalog."default",
    longitude numeric(11, 8),
    latitude numeric(10, 8),
    manufacturer text COLLATE pg_catalog."default",
    model text COLLATE pg_catalog."default",
    station_type text COLLATE pg_catalog."default",
    num_plugs integer,
    max_charging_power numeric(12, 3),
    max_discharging_power numeric(12, 3),
    dataset_id integer,
    ocpp_version varchar(10),

    fk_connector_id integer,
    fk_charging_point_type_id integer,
    CONSTRAINT "ChargingStation_pkey" PRIMARY KEY (id)
);


DROP TABLE IF EXISTS evinsights."User";

CREATE TABLE IF NOT EXISTS evinsights."User"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    orig_id text COLLATE pg_catalog."default",
    ev_id text COLLATE pg_catalog."default",
    ev_manufacturer text COLLATE pg_catalog."default",
    ev_model text COLLATE pg_catalog."default",
    ev_battery_capacity_kWh numeric(12, 2),
    ev_battery_type text COLLATE pg_catalog."default",
    ev_battery_useable_capacity numeric(12, 2),
    ev_v2g boolean,
    ev_max_charging_power numeric(12, 3),
    ev_max_discharging_power numeric(12, 3),
    dataset_id integer,
    fk_electric_vehicle_id integer,
    CONSTRAINT "User_pkey" PRIMARY KEY (id)
);

DROP TABLE IF EXISTS evinsights."ChargingStationForecast";

CREATE TABLE IF NOT EXISTS evinsights."ChargingStationForecast"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    date date,
    energy numeric(12, 3),
    connections integer,
    experiment_id text,
    run_id text,
    created_at timestamp with time zone,
    fk_charging_station_id integer,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS evinsights."UserForecast";

CREATE TABLE IF NOT EXISTS evinsights."UserForecast"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    date date,
    energy numeric(12, 3),
    duration integer,
    experiment_id text,
    run_id text,
    created_at timestamp with time zone,
    fk_user_id integer,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS evinsights."ChargingSession"
    ADD CONSTRAINT fk_charging_station_id FOREIGN KEY (fk_charging_station_id)
    REFERENCES evinsights."ChargingStation" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS evinsights."ChargingSession"
    ADD CONSTRAINT fk_dataset_id FOREIGN KEY (fk_dataset_id)
    REFERENCES evinsights."Dataset" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS evinsights."ChargingSession"
    ADD CONSTRAINT fk_user_id FOREIGN KEY (fk_user_id)
    REFERENCES evinsights."User" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS evinsights."ChargingStationForecast"
    ADD CONSTRAINT fk_charging_station_id FOREIGN KEY (fk_charging_station_id)
    REFERENCES evinsights."ChargingStation" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS evinsights."UserForecast"
    ADD CONSTRAINT fk_user_id FOREIGN KEY (fk_user_id)
    REFERENCES evinsights."User" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS evinsights."ChargingStation"
    ADD CONSTRAINT fk_connector_id FOREIGN KEY (fk_connector_id)
    REFERENCES evinsights."Connector" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS evinsights."ChargingStation"
    ADD CONSTRAINT fk_charging_point_type_id FOREIGN KEY (fk_charging_point_type_id)
    REFERENCES evinsights."ChargingPointType" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS evinsights."User"
    ADD CONSTRAINT fk_electric_vehicle_id FOREIGN KEY (fk_electric_vehicle_id)
    REFERENCES evinsights."ElectricVehicle" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;

-- Assigning permissions to the evinsights user
GRANT ALL PRIVILEGES ON DATABASE evinsights TO evinsights;
GRANT ALL PRIVILEGES ON SCHEMA evinsights TO evinsights;


-- It seems that although the evinsights user has permissions on the schema, the tables (specifically Dataset) were likely created by the postgres superuser (or another user), and evinsights wasn't granted explicit permissions on those specific tables. In PostgreSQL, granting permissions on a schema does not automatically grant permissions on existing tables within it, nor on future tables created by other users unless ALTER DEFAULT PRIVILEGES is used.

-- This ensures that any tables created by the postgres user in the evinsights schema will automatically be accessible to the evinsights user.

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA evinsights TO evinsights;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA evinsights TO evinsights;

